In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
len(np.linspace(0,10,11))

11

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.random.rand(3,3)

array([[0.20957852, 0.69774228, 0.00998876],
       [0.09852049, 0.83903238, 0.80945232],
       [0.9632319 , 0.12916792, 0.38768542]])

In [31]:
np.random.randn(2,3)

array([[ 0.10175799, -1.39133039, -0.62797035],
       [-0.85296672,  1.73004798, -1.61606413]])

In [32]:
np.random.randint(0,101,5)

array([ 7, 87, 43, 64, 36])

In [33]:
np.random.randint(0,101,(4,5))

array([[58, 89, 47, 45,  2],
       [21, 76, 72,  7, 11],
       [27, 27, 48, 39, 96],
       [49, 38, 19, 40, 13]])

In [39]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [41]:
arr = np.arange(0,25)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
ranarr = np.random.randint(0,101,10)

In [45]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [46]:
ranarr.max()

99

In [47]:
ranarr.min()

2

In [48]:
ranarr.argmax()

5

In [49]:
ranarr.dtype

dtype('int32')

In [50]:
arr.shape

(25,)